{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sparsemvn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sparseMVN_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sparseMVN/sparseMVN_{{ version }}.tar.gz
  sha256: e56c22e4bbf0960a4b912369550210163605d2bf6c1055524bdab05c093fa9ed

build:
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix >=1.3
  run:
    - r-base
    - r-matrix >=1.3

test:
  commands:
    - $R -e "library('sparseMVN')"           # [not win]
    - "\"%R%\" -e \"library('sparseMVN')\""  # [win]

about:
  home: https://braunm.github.io/sparseMVN/
  dev_url: https://github.com/braunm/sparseMVN/
  license: MPL-2.0
  summary: Computes multivariate normal (MVN) densities, and samples from MVN distributions, when the covariance or precision matrix is sparse.
  license_family: OTHER
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/r
